package com.example.hangman

object Phrases {

    val randomPhrases = arrayOf(
        "ALAS   DORADAS",
        "SOL     NACIENTE",
        "AMOR  ETERNO",
        "CIELO     ESTRELLADO",
        "TORMENTA  CALMA     ",
        "DULCE AMOR",
        "VOLAR LIBRE",
        "AIRE  FRESCO",
        "MAR      TRANQUILO",
        "FELIZ AÑO",
        "VIENTO SUAVE",
        "MAR AZUL",
        "RIO       CRISTALINO",
        "BOSQUE VERDE ",
        "CIELO AZUL  ",
        "UNA   MIRADA",
        "PALABRA AMABLE ",
        "JARDIN  FLORIDO",
        "BAILAR ALEGRE",
        "CASCADA HERMOSA",
        "CARICIA TIERNA  ",
        "BRISA SUAVE",
        "CANTAR ALEGRE ",
        "MIRADA TIERNA ",
        "FUEGO   ARDIENTE",
        "LUNA LLENA",
        "SOL     NACIENTE",
        "VOLAR  ALTO ",
        "BELLEZA NATURAL",
        "LUZ   BLANCA",
        "AMIGO FIEL ",
        "CIELO    DESPEJADO",
        "MAR   CALMO",
        "BESO   ROBADO",
        "CASCADA MAGICA  ",
        "LUNA    LUMINOSA",
        "MIRADA  PROFUNDA",
        "AIRE  LIMPIO",
        "BAILAR LIBRE",
        "SOL      BRILLANTE",
        "AMOR  ETERNO",
        "VIAJE CORTO",
        "LUZ   SUAVE",
        "FLORES BELLAS",
        "RIO      TRANQUILO",
        "SOL     RADIANTE",
        "VOLAR LIBRE",
        "NUEVA VIDA",
        "MAGA",
        "TANTAS VECES",
        "HABÍA BASTADO",
        "ASOMARME",
        "VINIENDO",
        "CENIZA",
        "OLIVO",
        "FLOTA",
        "SOBRE",
        "DEJABA",
        "DISTINGUIR",
        "FORMAS",
        "SILUETA",
        "DELGADA",
        "INSCRIBÍA",
        "ANDANDO",
        "DE UN LADO  A OTRO  ",
        "DETENIDA",
        "HIERRO",
        "INCLINADA",
        "NATURAL",
        "CRUZAR LA CALLE  ",
        "SUBIR LOSPELDAÑOS",
        "DELGADA",
        "CINTURA",
        "ACERCARME",
        "SONREÍA",
        "SORPRESA",
        "CONVENCIDA",
        "ENCUENTRO",
        "CASUAL",
        "NUESTRAS",
        "VIDAS",
        "QUE LA    GENTE CREA",
        "CITAS   PRECISAS",
        "NECESITA",
        "ESCRIBIRSE",
        "DENTÍFRICO",
        "AHORA",
        "TRANSLÚCIDA",
        "ASOMARÍA",
        "VIEJOS  PORTALES",
        "GHETTO",
        "ESTUVIERA",
        "CHARLANDO",
        "VENDEDORA",
        "PAPAS FRITAS",
        "COMIENDO SALCHICHA",
        "BOULEVARD",
        "MANERAS",
        "CAMINO",
        "HABITACIONES",
        "FALSOS",
        "ESTUDIANTES",
        "PARÍS",
        "TARJETA",
        "VENTANITA",
        "MOLDURAS",
        "BARATAS",
        "PAPELES",
        "CHILLONES",
        "TERRAZA",
        "CINECLUB",
        "AGACHADOS",
        "PATIO",
        "ANDÁBAMOS    SIN    BUSCARNOS",
        "PARECIDA",
        "AGOLPABA",
        "SILENCIO",
        "PAUSA FILOSA",
        "CRISTALINA",
        "PARAGÜAS MOJADO ",
        "BARRANCO",
        "ATARDECER HELADO    ",
        "ENCONTRADO",
        "MUCHÍSIMO",
        "COSTILLAS",
        "AUTOBUSES",
        "DISTRAÍDA",
        "PÁJAROS",
        "DIBUJITO",
        "CHAPARRÓN",
        "ORGULLOSA",
        "CATÁSTROFE",
        "RELÁMPAGOS",
        "DESTROZADA",
        "CAYENDO",
        "DESTELLOS",
        "LOCOS",
        "DIGNAMENTE",
        "VEREDA",
        "PUENTECITO",
        "BARRANCA",
        "PROFERÍAS",
        "VAGAMENTE",
        "RECONOCER",
        "WALKYRIA",
        "BARRANCO",
        "ENAMORADOS",
        "ABRAZADOS SEMEJANTES",
        "PELÍCULA",
        "HÚNGARA",
        "PISOTEADO",
        "NINGUNO",
        "RESORTES",
        "TERMINADO",
        "ESTÁBAMOS",
        "CONTENTOS",
        "JUEVES DE DICIEMBRE",
        "ORILLA",
        "DERECHA",
        "BEBER VINO EN EL     CAFECITO ",
        "MADAME",
        "VIAJES Y SORPRESAS",
        "ESPEJO",
        "TERRIBLE",
        "ESPANTOSA",
        "MÁQUINA",
        "AMARNOS",
        "DELANTE",
        "AMARILLA",
        "VELAS VERDES",
        "RENUNCIAS",
        "DESPEDIDAS",
        "PEQUEÑA",
        "LIBRERÍA",
        "PREGUNTAS",
        "ESTANTES",
        "DIFÍCIL",
        "CUCARACHA",
        "RELUCIENTE",
        "LIMPIEZA",
        "DELANTAL",
        "HANSEL Y  GRETEL    ",
        "ENVILECÍA",
        "FRACASO",
        "SIRENA",
        "ANTIGUOS",
        "APOSTABAS",
        "LOS    ÁNGELES",
        "MARIPOSAS",
        "DISTINGUIR",
        "DETENIDA"
    )
}